cloud:
  provider: gcp
  storageClass: pd-balanced
  ingressClass: gce

serviceAccount:
  annotations:
    iam.gke.io/gcp-service-account: signalgrid-lawful-intercept@{{ .Values.gcp.project }}.iam.gserviceaccount.com
