apiVersion: v1
kind: Service
metadata:
  name: smf-service
  namespace: signalgrid
  labels: { app.kubernetes.io/name: smf-service, signalgrid.io/domain: 5g-core }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 50161, targetPort: 50161 }]
  selector: { app.kubernetes.io/name: smf-service }
