apiVersion: v1
kind: Service
metadata:
  name: rap-service
  namespace: signalgrid
  labels: { app.kubernetes.io/name: rap-service, signalgrid.io/domain: roaming }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 50181, targetPort: 50181 }]
  selector: { app.kubernetes.io/name: rap-service }
