apiVersion: v1
kind: Service
metadata:
  name: nssf-service
  namespace: signalgrid
  labels: { app.kubernetes.io/name: nssf-service, signalgrid.io/domain: 5g-core }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 50164, targetPort: 50164 }]
  selector: { app.kubernetes.io/name: nssf-service }
