apiVersion: v1
kind: ConfigMap
metadata:
  name: lawful-intercept
  namespace: signalgrid
  labels: { app.kubernetes.io/name: lawful-intercept, signalgrid.io/domain: regulatory }
data:
  LOG_LEVEL: info
  PORT: "50280"
