apiVersion: v1
kind: ConfigMap
metadata:
  name: dunning-service
  namespace: signalgrid
  labels: { app.kubernetes.io/name: dunning-service, signalgrid.io/domain: billing }
data:
  LOG_LEVEL: info
  PORT: "50103"
