testkube-api:
  image: { repository: kubeshop/testkube-api-server, tag: 2.1.0 }
  ingress: { enabled: true, hosts: [{ host: testkube.signalgrid.internal }] }
testkube-dashboard:
  enabled: true
  ingress: { enabled: true, hosts: [{ host: testkube-dash.signalgrid.internal }] }
mongodb: { enabled: true }
