exclude_paths:
  - vendor/
  - node_modules/
  - target/
  - build/
  - _build/
  - .terraform/
detectors:
  - AWS
  - GCP
  - Azure
  - GitHub
  - GitLab
  - Slack
  - Stripe
  - HashiCorp
  - Twilio
