apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: signalgrid
build:
  artifacts: []   # filled in per service in src/<domain>/<service>/skaffold.yaml
deploy:
  helm:
    releases: []  # filled in per service
