apiVersion: v1
kind: ConfigMap
metadata:
  name: ocs-service
  namespace: signalgrid
  labels: { app.kubernetes.io/name: ocs-service, signalgrid.io/domain: roaming }
data:
  LOG_LEVEL: info
  PORT: "50182"
