apiVersion: v1
kind: Service
metadata:
  name: cm-service
  namespace: signalgrid
  labels: { app.kubernetes.io/name: cm-service, signalgrid.io/domain: nms }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 50142, targetPort: 50142 }]
  selector: { app.kubernetes.io/name: cm-service }
