apiVersion: v1
kind: Service
metadata:
  name: alarm-correlation
  namespace: signalgrid
  labels: { app.kubernetes.io/name: alarm-correlation, signalgrid.io/domain: nms }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 50143, targetPort: 50143 }]
  selector: { app.kubernetes.io/name: alarm-correlation }
