apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata: { name: signalgrid-gcp, namespace: argocd }
spec:
  generators:
    - git:
        repoURL: https://github.com/prabhat-roy/SignalGrid.git
        revision: HEAD
        directories: [{ path: helm/charts/* }]
  template:
    metadata:
      name: '{{path.basename}}-gcp'
      labels: { cloud: gcp, signalgrid.io/managed-by: argocd }
    spec:
      project: signalgrid
      source:
        repoURL: https://github.com/prabhat-roy/SignalGrid.git
        targetRevision: HEAD
        path: '{{path}}'
        helm:
          valueFiles: [values.yaml, values-gcp.yaml]
      destination:
        server: https://kubernetes.default.svc
        namespace: signalgrid
      syncPolicy:
        automated: { prune: true, selfHeal: true }
        syncOptions: [CreateNamespace=true, ServerSideApply=true]
