apiVersion: v1
kind: Service
metadata:
  name: support-service
  namespace: signalgrid
  labels: { app.kubernetes.io/name: support-service, signalgrid.io/domain: customer }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 50221, targetPort: 50221 }]
  selector: { app.kubernetes.io/name: support-service }
