apiVersion: v1
kind: ConfigMap
metadata:
  name: geo-address-service
  namespace: signalgrid
  labels: { app.kubernetes.io/name: geo-address-service, signalgrid.io/domain: platform }
data:
  LOG_LEVEL: info
  PORT: "51013"
