apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata: { name: signalgrid, namespace: argocd }
spec:
  description: SignalGrid platform applications
  sourceRepos: [https://github.com/prabhat-roy/SignalGrid.git]
  destinations:
    - { namespace: signalgrid,    server: https://kubernetes.default.svc }
    - { namespace: 'signalgrid-*', server: https://kubernetes.default.svc }
  clusterResourceWhitelist:    [{ group: '*', kind: '*' }]
  namespaceResourceWhitelist:  [{ group: '*', kind: '*' }]
