apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-preferences-service
  namespace: signalgrid
  labels: { app.kubernetes.io/name: notification-preferences-service, signalgrid.io/domain: platform }
data:
  LOG_LEVEL: info
  PORT: "51005"
