apiVersion: v1
kind: Service
metadata:
  name: subscriber-sso
  namespace: signalgrid
  labels: { app.kubernetes.io/name: subscriber-sso, signalgrid.io/domain: identity }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 50021, targetPort: 50021 }]
  selector: { app.kubernetes.io/name: subscriber-sso }
