apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata: { name: mediation-service, namespace: signalgrid }
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mediation-service
  minReplicas: 2
  maxReplicas: 30
  metrics:
    - type: Resource
      resource: { name: cpu, target: { type: Utilization, averageUtilization: 70 } }
    - type: Resource
      resource: { name: memory, target: { type: Utilization, averageUtilization: 75 } }
