apiVersion: v1
kind: ConfigMap
metadata:
  name: webhook-delivery-service
  namespace: signalgrid
  labels: { app.kubernetes.io/name: webhook-delivery-service, signalgrid.io/domain: platform }
data:
  LOG_LEVEL: info
  PORT: "51004"
