apiVersion: v1
kind: Service
metadata:
  name: fra-service
  namespace: signalgrid
  labels: { app.kubernetes.io/name: fra-service, signalgrid.io/domain: fraud }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 50260, targetPort: 50260 }]
  selector: { app.kubernetes.io/name: fra-service }
