apiVersion: v1
kind: ConfigMap
metadata:
  name: file-upload-service
  namespace: signalgrid
  labels: { app.kubernetes.io/name: file-upload-service, signalgrid.io/domain: platform }
data:
  LOG_LEVEL: info
  PORT: "51011"
