[SERVICE]
    Daemon Off
    HTTP_Server On
    HTTP_Port 2020
    Parsers_File parsers.conf

[INPUT]
    Name tail
    Path /var/log/containers/*signalgrid*.log
    Parser docker
    Tag kube.*

[FILTER]
    Name modify
    Match *
    Add cluster signalgrid

# Mask MSISDN/customer-account-no in logs (GDPR)
[FILTER]
    Name modify
    Match *
    Rename msisdn msisdn_redacted

[OUTPUT]
    Name loki
    Match kube.*
    host loki
    port 3100
    labels job=signalgrid, app=$kubernetes['labels']['app.kubernetes.io/name']
