apiVersion: v1
kind: ConfigMap
metadata:
  name: fm-service
  namespace: signalgrid
  labels: { app.kubernetes.io/name: fm-service, signalgrid.io/domain: nms }
data:
  LOG_LEVEL: info
  PORT: "50140"
