apiVersion: v1
kind: Service
metadata:
  name: emergency-service
  namespace: signalgrid
  labels: { app.kubernetes.io/name: emergency-service, signalgrid.io/domain: regulatory }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 50282, targetPort: 50282 }]
  selector: { app.kubernetes.io/name: emergency-service }
