apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: signalgrid
  labels: { app.kubernetes.io/name: payment-service, signalgrid.io/domain: customer }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 50220, targetPort: 50220 }]
  selector: { app.kubernetes.io/name: payment-service }
