apiVersion: v1
kind: ConfigMap
metadata:
  name: pos-service
  namespace: signalgrid
  labels: { app.kubernetes.io/name: pos-service, signalgrid.io/domain: channel }
data:
  LOG_LEVEL: info
  PORT: "50241"
