apiVersion: v1
kind: Service
metadata:
  name: operator-sso
  namespace: signalgrid
  labels: { app.kubernetes.io/name: operator-sso, signalgrid.io/domain: identity }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 50022, targetPort: 50022 }]
  selector: { app.kubernetes.io/name: operator-sso }
