zitadel:
  masterkey: change-me-32-bytes-minimum
  configmapConfig:
    ExternalDomain: zitadel.signalgrid.internal
    ExternalSecure: true
    ExternalPort: 443
ingress:
  enabled: true
  hosts: [{ host: zitadel.signalgrid.internal }]
