apiVersion: v1
kind: ConfigMap
metadata:
  name: mfa-service
  namespace: signalgrid
  labels: { app.kubernetes.io/name: mfa-service, signalgrid.io/domain: identity }
data:
  LOG_LEVEL: info
  PORT: "50023"
